[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[phases.install]
dependsOn = ["build"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/crudapp-0.0.1-SNAPSHOT.jar"
