services:
  - type: web
    name: controle-auditorias
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/crudapp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: SERVER_PORT
        value: 8080
    healthCheckPath: /login
